Repository kubeflow/mxnet-operator, pull requests merged in 2019-03, with the labels that each got.

#21 fix bug: tunerTracker and tunerServer won't stop while tuner has been completed
  pkg/controller.v2/mxnet/status.go
Labels: approved, lgtm, ok-to-test, size/XS

#22 Change working directory in the tune mode
  examples/mxnet-operator.v2/tune/Dockerfile
  examples/mxnet-operator.v2/tune/mx_job_tune_gpu.yaml
  examples/mxnet-operator.v2/tune/start-job.py
Labels: approved, lgtm, ok-to-test, size/S

#23 Update examples with correct path
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#25 fix Dockerfile to follow latest change and rearrange directory
  .gitignore
  Dockerfile
  manifests/deployment.yaml
  manifests/rbac.yaml
Labels: approved, lgtm, size/M

#26 Update README to reflect latest change
  README.md
Labels: approved, lgtm, size/L
