Repository kubeflow/mxnet-operator, pull requests merged in 2019-05, with the labels that each got.

#33 fix UT compile error
  pkg/controller.v1beta1/mxnet/controller_test.go
  pkg/controller.v1beta1/mxnet/job_test.go
  pkg/controller.v1beta1/mxnet/pod_test.go
  pkg/controller.v1beta1/mxnet/service_test.go
  pkg/controller.v1beta1/mxnet/status_test.go
Labels: approved, lgtm, ok-to-test, size/L

#35 Use kube-batch as scheduler by default when gang-scheduling is enabled
  pkg/controller.v1beta1/mxnet/pod.go
Labels: approved, lgtm, ok-to-test, size/S

#37 add travis.yml to mxnet-operator
  .travis.yml
  cmd/mxnet-operator.v1beta1/app/options/options.go
  cmd/mxnet-operator.v1beta1/app/server.go
  linter_config.json
  pkg/apis/mxnet/v1beta1/defaults.go
  pkg/apis/mxnet/validation/validation.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/doc.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/fake/fake_mxjob.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/fake/fake_mxnet_client.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/mxjob.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/mxnet_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/mxnet/interface.go
  pkg/client/informers/externalversions/mxnet/v1beta1/interface.go
  pkg/client/informers/externalversions/mxnet/v1beta1/mxjob.go
  pkg/client/listers/mxnet/v1beta1/expansion_generated.go
  pkg/client/listers/mxnet/v1beta1/mxjob.go
  pkg/common/util/v1beta1/testutil/const.go
  pkg/common/util/v1beta1/testutil/mxjob.go
  pkg/common/util/v1beta1/unstructured/informer.go
  pkg/controller.v1beta1/mxnet/controller.go
  pkg/controller.v1beta1/mxnet/controller_test.go
  pkg/controller.v1beta1/mxnet/informer.go
  pkg/controller.v1beta1/mxnet/job.go
  pkg/controller.v1beta1/mxnet/pod.go
  pkg/controller.v1beta1/mxnet/pod_test.go
  pkg/controller.v1beta1/mxnet/service.go
  pkg/controller.v1beta1/mxnet/status.go
  pkg/controller.v1beta1/mxnet/status_test.go
  pkg/controller.v1beta1/mxnet/util.go
  pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, ok-to-test, size/L

#40 Implement ActiveDeadlineSeconds and BackoffLimit
  pkg/apis/mxnet/v1/types.go
  pkg/apis/mxnet/v1/zz_generated.deepcopy.go
  pkg/common/util/v1/testutil/mxjob.go
  pkg/common/util/v1/testutil/pod.go
  pkg/controller.v1/mxnet/controller.go
  pkg/controller.v1/mxnet/controller_test.go
  pkg/controller.v1/mxnet/job.go
  pkg/controller.v1/mxnet/job_test.go
  pkg/controller.v1/mxnet/pod.go
  pkg/controller.v1/mxnet/status.go
  pkg/controller.v1/mxnet/status_test.go
  pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, ok-to-test, size/XL

#42 add wackxu to OWNERS
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#41 Sync with tf-operator
  Gopkg.lock
  Gopkg.toml
  cmd/mxnet-operator.v1/app/options/options.go
  cmd/mxnet-operator.v1/app/server.go
  pkg/controller.v1/mxnet/controller.go
  pkg/controller.v1/mxnet/status.go
  pkg/controller.v1beta1/mxnet/controller.go
  pkg/controller.v1beta1/mxnet/status.go
  vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/jobcontroller.go
  vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/pod.go
  vendor/github.com/kubeflow/tf-operator/pkg/control/pod_control.go
  vendor/github.com/kubeflow/tf-operator/pkg/control/service_control.go
Labels: approved, lgtm, ok-to-test, size/L

#43 add uuid to id for leader election
  Gopkg.lock
  cmd/mxnet-operator.v1/app/server.go
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
Labels: approved, lgtm, ok-to-test, size/XXL
