Repository kubeflow/mxnet-operator, pull requests merged in 2020-05, with the labels that each got.

#77 Remove Travis buddy webhook
  .travis.yml
Labels: approved, lgtm, size/XS

#75 Add Jeffwan to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#78 Add release document
  RELEASE.md
Labels: approved, lgtm, size/M

#76 Migrate controller implementation to kubeflow/common fashion
  .gitignore
  cmd/mxnet-operator.v1/app/server.go
  go.mod
  go.sum
  pkg/apis/mxnet/v1/constants.go
  pkg/apis/mxnet/v1/defaults.go
  pkg/apis/mxnet/v1/defaults_test.go
  pkg/apis/mxnet/v1/types.go
  pkg/apis/mxnet/v1/util.go
  pkg/apis/mxnet/v1/util_test.go
  pkg/apis/mxnet/v1/zz_generated.deepcopy.go
  pkg/apis/mxnet/validation/validation.go
  pkg/apis/mxnet/validation/validation_test.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/informers/externalversions/mxnet/interface.go
  pkg/common/util/v1/testutil/mxjob.go
  pkg/common/util/v1/testutil/util.go
  pkg/controller.v1/mxnet/controller.go
  pkg/controller.v1/mxnet/controller_test.go
  pkg/controller.v1/mxnet/informer.go
  pkg/controller.v1/mxnet/job.go
  pkg/controller.v1/mxnet/job_test.go
  pkg/controller.v1/mxnet/mxnet.go
  pkg/controller.v1/mxnet/pod.go
  pkg/controller.v1/mxnet/pod_test.go
  pkg/controller.v1/mxnet/service.go
  pkg/controller.v1/mxnet/service_test.go
  pkg/controller.v1/mxnet/status.go
  pkg/controller.v1/mxnet/status_test.go
  pkg/controller.v1/mxnet/util.go
  pkg/util/k8sutil/client.go
Labels: approved, lgtm, size/XXL
