Repository kubeflow/mxnet-operator, pull requests merged in 2020-04, with the labels that each got.

#60 Add myself to OWNERS
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#61 Enhancements on README.md
  README.md
Labels: approved, lgtm, size/M

#64 Add Jiaxin to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#63 Add initial list of adopters
  ADOPTERS.md
Labels: approved, lgtm, size/S

#68 Add mxnet-operator v1 examples
  README.md
  examples/train/Dockerfile
  examples/train/mx_job_dist_gpu_v1.yaml
  examples/train/mx_job_dist_gpu_v1beta1.yaml
  examples/tune/Dockerfile
  examples/tune/README.md
  examples/tune/auto-tuning.py
  examples/tune/mx_job_tune_gpu_v1.yaml
  examples/tune/mx_job_tune_gpu_v1beta1.yaml
  examples/tune/start-job.py
  examples/v1beta1/train/Dockerfile
  examples/v1beta1/train/train_mnist.py
  examples/v1beta1/tune/README.md
Labels: approved, lgtm, size/L

#69 Fix Python script name and add links
  examples/tune/README.md
Labels: approved, lgtm, size/S

#70 Create separate clusterrole for mxnet-operator
  README.md
  manifests/cluster-role-binding.yaml
  manifests/cluster-role.yaml
  manifests/deployment.yaml
  manifests/service-account.yaml
Labels: approved, lgtm, size/M

#71 Add Kustomize package deployable on its own
  README.md
  manifests/kustomization.yaml
Labels: approved, lgtm, size/M

#73 Remove go.mod suffix when grabbing code-generator version
  hack/update-codegen.sh
Labels: approved, lgtm, size/XS

#74 Fix the reconcile flow
  pkg/controller.v1/mxnet/controller.go
Labels: approved, lgtm, size/M
