Repository kubeflow/mxnet-operator, pull requests merged in 2021-03, with the labels that each got.

#90 MXNet Operator: Move manifests development upstream
  manifests/mxnet-operator/base/cluster-role-binding.yaml
  manifests/mxnet-operator/base/cluster-role.yaml
  manifests/mxnet-operator/base/crd.yaml
  manifests/mxnet-operator/base/deployment.yaml
  manifests/mxnet-operator/base/kustomization.yaml
  manifests/mxnet-operator/base/service-account.yaml
  manifests/mxnet-operator/overlays/application/application.yaml
  manifests/mxnet-operator/overlays/application/kustomization.yaml
  pkg/apis/mxnet/v1/zz_generated.deepcopy.go
  pkg/apis/mxnet/v1/zz_generated.defaults.go
  pkg/apis/mxnet/v1beta1/zz_generated.deepcopy.go
  pkg/apis/mxnet/v1beta1/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/mxnet/v1/doc.go
  pkg/client/clientset/versioned/typed/mxnet/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/mxnet/v1/fake/fake_mxjob.go
  pkg/client/clientset/versioned/typed/mxnet/v1/fake/fake_mxnet_client.go
  pkg/client/clientset/versioned/typed/mxnet/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/mxnet/v1/mxjob.go
  pkg/client/clientset/versioned/typed/mxnet/v1/mxnet_client.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/doc.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/fake/fake_mxjob.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/fake/fake_mxnet_client.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/mxjob.go
  pkg/client/clientset/versioned/typed/mxnet/v1beta1/mxnet_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/mxnet/interface.go
  pkg/client/informers/externalversions/mxnet/v1/interface.go
  pkg/client/informers/externalversions/mxnet/v1/mxjob.go
  pkg/client/informers/externalversions/mxnet/v1beta1/interface.go
  pkg/client/informers/externalversions/mxnet/v1beta1/mxjob.go
  pkg/client/listers/mxnet/v1/expansion_generated.go
  pkg/client/listers/mxnet/v1/mxjob.go
  pkg/client/listers/mxnet/v1beta1/expansion_generated.go
  pkg/client/listers/mxnet/v1beta1/mxjob.go
Labels: approved, size/L

#91 MXNet Operator: Consolidate manifests
  README.md
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/base/user-cluster-roles.yaml
  manifests/mxnet-operator/base/cluster-role-binding.yaml
  manifests/mxnet-operator/base/crd.yaml
  manifests/mxnet-operator/base/deployment.yaml
  manifests/mxnet-operator/base/kustomization.yaml
  manifests/mxnet-operator/base/service-account.yaml
  manifests/mxnet-operator/overlays/application/application.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/v1/deployment.yaml
  manifests/overlays/v1/kustomization.yaml
  manifests/overlays/v1beta1/kustomization.yaml
Labels: approved, lgtm, size/L

#93 Update mxnet operator image to v1.1.0
  manifests/base/kustomization.yaml
  manifests/overlays/v1/deployment.yaml
Labels: approved, size/XS

#94 Update README.md to use v1 manifest and samples
  README.md
Labels: approved, size/M
